# workflow -> checkout -> setup-runner -> build -> jar

name: 01-task
on: workflow_dispatch
jobs:
    app:
      runs-on: ubuntu-latest
      steps:
        - name: checkout 
          uses: actions/checkout@v4
        - name: setup java 
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '21'
        - name: buid 
          run: mvn install
    