name: 05-01-actions
#on: push
on: workflow_dispatch
jobs: 
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code 
      - uses: actions/setup-java@v4
        name: setup java 
        with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '21'
        